version: '3.8'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  secondary1:
    build:
      context: .
      dockerfile: Dockerfile.secondary
    networks:
      - mynetwork

  secondary2:
    build:
      context: .
      dockerfile: Dockerfile.secondary
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
      - "8002:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
    environment:
      - MASTER_INTERNAL_IP=172.22.0.2

networks:
  mynetwork:
    driver: bridge
